import {chromium} from '@playwright/test';
import {build} from 'esbuild';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
const bundle=await build({entryPoints:['src/client.ts'],bundle:true,format:'iife',globalName:'WorkbenchModule',platform:'browser',write:false,target:'es2022'});
const browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1234/chrome-linux/headless_shell',args:['--no-sandbox']});
const page=await browser.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:9119/sessions');
await page.waitForFunction(()=>!!window.__HERMES_PLUGIN_SDK__);
await page.addScriptTag({content:bundle.outputFiles[0].text});
await mkdir('evidence',{recursive:true});
const result=await page.evaluate(async()=>{
 const client=new WorkbenchModule.WorkbenchClient(window.__HERMES_PLUGIN_SDK__);
 window.testClient=client; window.testEvents=[];
 client.onEvent(e=>window.testEvents.push({type:e.type,session_id:e.session_id,payload:e.payload}));
 await client.connect();
 const list=await client.listSessions(5);
 const session=await client.createSession({title:'Workbench live verification',cwd:'/opt/data/hermes-workbench/evidence'});
 window.testSession=session;
 return {connection:client.connectionState,listed:list.length,session};
});
console.log('CREATE',JSON.stringify(result));
await page.evaluate(async()=>{await window.testClient.submit(window.testSession.session_id,'This is a bounded browser Workbench verification. Use your terminal tool to write exactly WORKBENCH_NATIVE_OK followed by a newline to /opt/data/hermes-workbench/evidence/native-proof.txt. Then read that exact file with your terminal tool and reply with its contents. Do not change any other files, skills, memory, config, or repositories. Do not delegate.');});
await page.waitForFunction(()=>window.testEvents.some(e=>e.type==='message.complete'&&e.session_id===window.testSession.session_id),null,{timeout:240000});
const after=await page.evaluate(async()=>({events:window.testEvents,history:await window.testClient.history(window.testSession.session_id),state:window.testClient.state}));
await writeFile('evidence/native-smoke.json',JSON.stringify({create:result,after,errors},null,2));
console.log('EVENTS',after.events.map(e=>e.type)); console.log('HISTORY',JSON.stringify(after.history)); console.log('ERRORS',errors);
console.log('PROOF',await readFile('evidence/native-proof.txt','utf8'));
await page.evaluate(()=>window.testClient.disconnect());
await browser.close();
